### ISSUE TITLE
_on_connect() missing 1 required positional argument: 'initial_data'

### ISSUE THREAD

**Issue by pschakravarthi** [groupby/hubot-hangups#35]
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Traceback (most recent call last):
  File "/cbot/node_modules/hubot-hangups/HangoutsBot/hangupsbot.py", line 137, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 373, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/site-packages/hangups/client.py", line 140, in connect
    yield from self._listen_future
  File "/usr/lib64/python3.4/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 297, in _wakeup
    future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.4/site-packages/hangups/channel.py", line 211, in listen
    yield from self._longpoll_request()
  File "/usr/lib/python3.4/site-packages/hangups/channel.py", line 321, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/lib/python3.4/site-packages/hangups/channel.py", line 347, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/lib/python3.4/site-packages/hangups/event.py", line 60, in fire
    yield from gen
  File "/usr/lib/python3.4/site-packages/hangups/event.py", line 58, in fire
    gen = observer(*args, **kwargs)
TypeError: _on_connect() missing 1 required positional argument: 'initial_data'

**Comment by BlackHallDigital** [comment]
Getting the same
